#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2024 Saso Kiselkov. All rights reserved.

source ../build_dep.common

CGLM="cglm-0.7.9.tar.bz2"
CGLM_DIR="cglm-0.7.9"

if [[ "$do_clean" = "1" ]]; then
	rm -rf "${CGLM_DIR}"
elif ! [ -d "${CGLM_DIR}" ]; then
	tar xjf "${CGLM}"
fi
