#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2017 Saso Kiselkov. All rights reserved.

while getopts "cd" opt; do
	case $opt in
	c) export do_clean=1 ;;
	d) export do_dll=1 ;;
	esac
done

( cd zlib && ./build_zlib_deps ) && \
    ( cd libpng && ./build_libpng_deps ) && \
    ( cd freetype && ./build_freetype_deps ) && \
    ( cd cairo && ./build_cairo_deps ) && \
    ( cd opus && ./build_opus_deps ) && \
    ( cd ssl && ./build_ssl_deps ) && \
    ( cd curl && ./build_curl_deps ) && \
    ( cd shapelib && ./build_shapelib_deps ) && \
    ( cd ocr && ./build_ocr_deps ) && \
    ( cd lzma/qmake && if [ $(uname) = Darwin ]; then \
    ./build-mac else ./build-win-lin ; fi )
