#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2017 Saso Kiselkov. All rights reserved.

OUTPUT=libacfutils-redist

function install_platform() {
	PLATFORM="$1"
	HDRS="$2"
	LIBS="$3"

	mkdir -p "$OUTPUT/$PLATFORM/include" "$OUTPUT/$PLATFORM/lib"

	cp -r ${HDRS} "$OUTPUT/$PLATFORM"
	cp -r ${LIBS} "$OUTPUT/$PLATFORM/lib"
}

rm -rf "$OUTPUT"

mkdir -p "$OUTPUT/include"
cp -r src/acfutils glew/GL "$OUTPUT/include"
cp README-redist.md "$OUTPUT/README.md"

case $(uname) in
Linux)
	HDRS_WIN64=(
		cairo/cairo-win-64/include
		freetype/freetype-win-64/include
	)
	LIBS_WIN64=(
		qmake/win64/acfutils.dll
		qmake/win64/acfutils.lib
	)
	HDRS_LIN64=(
		cairo/cairo-linux-64/include
		freetype/freetype-linux-64/include
	)
	LIBS_LIN64=(
		qmake/lin64/libacfutils.a
		cairo/cairo-linux-64/lib/libcairo.a
		cairo/pixman-linux-64/lib/libpixman-1.a
		freetype/freetype-linux-64/lib/libfreetype.a
		libpng/libpng-linux-64/lib/libpng16.a
		opus/opusfile-linux-64/lib/libopusfile.a
		opus/opus-linux-64/lib/libopus.a
		opus/opusfile-linux-64/lib/libopusurl.a
		opus/libogg-linux-64/install/lib/libogg.a
		zlib/zlib-linux-64/lib/libz.a
	)

	install_platform "win64" "${HDRS_WIN64[*]}" "${LIBS_WIN64[*]}"
	install_platform "lin64" "${HDRS_LIN64[*]}" "${LIBS_LIN64[*]}"

	;;
Darwin)
	HDRS_MAC64=(
		cairo/cairo-mac-64/include
		freetype/freetype-mac-64/include
	)
	LIBS_MAC64=(
		qmake/mac64/libacfutils.a
		cairo/cairo-mac-64/lib/libcairo.a
		cairo/pixman-mac-64/lib/libpixman-1.a
		freetype/freetype-mac-64/lib/libfreetype.a
		libpng/libpng-mac-64/lib/libpng16.a
		opus/opusfile-mac-64/lib/libopusfile.a
		opus/opusfile-mac-64/lib/libopusurl.a
		opus/opus-mac-64/lib/libopus.a
		opus/libogg-mac-64/install/lib/libogg.a
		zlib/zlib-mac-64/lib/libz.a
	)

	install_platform "mac64" "${HDRS_MAC64[@]}" "${LIBS_MAC64[@]}"

	;;
*)
	echo "Unknown platform" >&2
	exit 1
	;;
esac
