#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2019 Saso Kiselkov. All rights reserved.

OUTPUT=libacfutils-redist
MINGWROOT="/usr/x86_64-w64-mingw32"

STATIC_LIBS=(
	'cairo/cairo-%PLATFORM%/lib/libcairo.a'
	'freetype/freetype-%PLATFORM%/lib/libfreetype.a'
	'cairo/pixman-%PLATFORM%/lib/libpixman-1.a'
	'libpng/libpng-%PLATFORM%/lib/libpng16.a'
	'opus/opusfile-%PLATFORM%/lib/libopusfile.a'
	'opus/opus-%PLATFORM%/lib/libopus.a'
	'opus/opusfile-%PLATFORM%/lib/libopusurl.a'
	'opus/libogg-%PLATFORM%/install/lib/libogg.a'

	'shapelib/libproj-%PLATFORM%/lib/libproj.a'
	'shapelib/libshape-%PLATFORM%/lib/libshp.a'

	'curl/libcurl-%PLATFORM%/lib/libcurl.a'
	'ssl/openssl-%PLATFORM%/lib/libssl.a'
	'ssl/openssl-%PLATFORM%/lib/libcrypto.a'
	'libxml2/libxml2-%PLATFORM%/lib/libxml2.a'
	'pcre2/pcre2-%PLATFORM%/lib/libpcre2-8.a'

	'libiconv/libiconv-%PLATFORM%/lib/libcharset.a'
	'libiconv/libiconv-%PLATFORM%/lib/libiconv.a'

	'zlib/zlib-%PLATFORM%/lib/libz.a'
	'lzma/qmake/%PLATFORM%/liblzma.a'
)

function repack_lib() {
	INLIB="$1"
	OUTLIB="$2"
	EXCLUDED="$3"

	(
		DIR="/tmp/build_redist.$$"
		rm -rf "$DIR" && mkdir -p "$DIR"
		cd "$DIR"
		ar x "$INLIB"
		rm $EXCLUDED
		ar rcs "$OUTLIB" *
		cd ..
		rm -r "$DIR"
	)
}

function install_platform() {
	PLATFORM="$1"
	HDRS="$2"
	LIBS="$3"
	SRCS="$4"

	case "$PLATFORM" in
	mingw64|win64)
		LONG_PLATFORM="win-64"
		;;
	lin64)
		LONG_PLATFORM="linux-64"
		;;
	mac64)
		LONG_PLATFORM="mac-64"
		;;
	esac

	mkdir -p "$OUTPUT/$PLATFORM/include" "$OUTPUT/$PLATFORM/lib"

	cp -r ${HDRS} "$OUTPUT/$PLATFORM/include"
	cp -r ${LIBS} "$OUTPUT/$PLATFORM/lib"
	if [ -z "$INSTALL_SHARED" ]; then
		for FILE in ${STATIC_LIBS[*]}; do
			PLATFORM_FILE="$(echo "$FILE" | \
			    sed "s/%PLATFORM%/$LONG_PLATFORM/g")"
			cp "$PLATFORM_FILE" "$OUTPUT/$PLATFORM/lib"
		done
	fi
	if [ -n "$SRCS" ]; then
		mkdir -p "$OUTPUT/$PLATFORM/src"
		cp -r ${SRCS} "$OUTPUT/$PLATFORM/src"
	fi
}

while getopts "d" opt; do
	case "$opt" in
	d)
		dll="-d"
		;;
	esac
done

rm -rf "$OUTPUT"

mkdir -p "$OUTPUT/include"
cp -r src/acfutils cglm/cglm-0.7.9/include/cglm "$OUTPUT/include"
cp README-redist.md "$OUTPUT/README.md"

case $(uname) in
Linux)
	( cd qmake && ./build-win-lin $dll ) || exit 1

	DLL_VERSION="$(git describe --abbrev=0 --tags | \
	    sed 's/[[:alpha:].]//g; s/^0//g')"
	HDRS_WIN64=(
		cairo/cairo-win-64/include/cairo/*
		freetype/freetype-win-64/include/freetype2/*
		glew/glew-*-win-64/install/include/GL
	)
	LIBS_WIN64=(
		"qmake/win64/acfutils${DLL_VERSION}.dll"
		"qmake/win64/libacfutils${DLL_VERSION}.a"
	)
	LIBS_MINGW64=(
		'qmake/win64/libacfutils.a'
		glew/glew-*-win-64/install/lib/libglew32mx.a
		$(x86_64-w64-mingw32-gcc -print-libgcc-file-name)
		$(x86_64-w64-mingw32-gcc -print-file-name=libgcc_eh.a)
	)
	HDRS_LIN64=(
		cairo/cairo-linux-64/include/cairo/*
		freetype/freetype-linux-64/include/freetype2/*
		glew/glew-*-linux-64/install/include/GL
	)
	LIBS_LIN64=(
		glew/glew-*-linux-64/install/lib64/libGLEWmx.a
		'qmake/lin64/libacfutils.a'
	)

	[ -f "qmake/win64/acfutils${DLL_VERSION}.dll" ] && \
	    INSTALL_SHARED=1 install_platform "win64" "${HDRS_WIN64[*]}" \
	    "${LIBS_WIN64[*]}"
	[ -f "qmake/win64/libacfutils.a" ] && \
	    install_platform "mingw64" "${HDRS_WIN64[*]}" \
	    "${LIBS_MINGW64[*]}"
	install_platform "lin64" "${HDRS_LIN64[*]}" "${LIBS_LIN64[*]}"

	;;
Darwin)
	( cd qmake && ./build-mac ) || exit 1

	HDRS_MAC64=(
		cairo/cairo-mac-64/include/cairo/*
		freetype/freetype-mac-64/include/freetype2/*
		glew/glew-*-mac-64/install/include/GL
	)
	LIBS_MAC64=(
		glew/glew-*-mac-64/install/lib/libGLEWmx.a
		qmake/mac64/libacfutils.a
	)

	install_platform "mac64" "${HDRS_MAC64[*]}" "${LIBS_MAC64[*]}"

	;;
*)
	echo "Unknown platform" >&2
	exit 1
	;;
esac
