#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2017 Saso Kiselkov. All rights reserved.

OUTPUT=libacfutils-redist

LIBS=(
	qmake/win64/acfutils.dll
	qmake/win64/acfutils.lib
)
HDR_DIRS=(
	glew/GL
	cairo/cairo-win-64/include/cairo
	freetype/freetype-win-64/include/freetype2
)

mkdir -p "$OUTPUT/lib" "$OUTPUT/include"
cp -r ${LIBS[@]} "$OUTPUT/lib"
cp -r ${HDR_DIRS[@]} "$OUTPUT/include"
cp -r src/acfutils "$OUTPUT/include"
