#!/bin/sh

# For Ubuntu 14.04, also upgrade to cmake 3.x from the following PPA:
# sudo add-apt-repository ppa:george-edison55/cmake-3.x
# sudo apt-get update
# sudo apt-get install cmake

sudo apt-get install \
    build-essential \
    cmake \
    libglu1-mesa-dev \
    pkg-config \
    qt4-qmake \
    qt4-dev-tools \
    automake \
    autoconf \
    libxcursor-dev \
    mingw-w64-x86-64-dev \
    gcc-mingw-w64-x86-64 \
    g++-mingw-w64-x86-64
