#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2020 Saso Kiselkov. All rights reserved.

# This file needs to be called from your makefile when using libacfutil.
# It produces the necessary cflags and libs to include all the build-time
# and link-time dependencies of libacfutils.
#
# You should invoke this script in one of the following two ways:
#
# 1) to generate CFLAGS:
#	$ <path_to_libacfutils>/pkg-config-deps 'ARCH' --cflags
# 1) to generate LDFLAGS:
#	$ <path_to_libacfutils>/pkg-config-deps 'ARCH' --libs
#
# Where 'ARCH' is should be one of: 'win-64', 'win-32', 'linux-64',
# 'linux-32' 'mac-64' and 'mac-32' (depending on the target being built for).

STATIC_OPENAL=0

cd "$(dirname "$0")"

ARCH="$1"
shift
if [[ "$1" = "--whole-archive" ]]; then
	if [[ "$(uname)" != Darwin ]]; then
		WHOLE_ARCH_ON="-Wl,--whole-archive"
		WHOLE_ARCH_OFF="-Wl,--no-whole-archive"
	fi
	shift
else
	WHOLE_ARCH_ON=""
	WHOLE_ARCH_OFF=""
fi

# The order of arguments we pass to pkg-config is important. We must list
# dependencies FOLLOWING the dependents (so e.g. zlib AFTER libpng).
if [[ "$1" = "--static-openal" ]]; then
	if [ -f "openal-soft/openal-soft-1.20.1-$ARCH/build/install/lib/pkgconfig/openal.pc" ]; then
		PACKAGES="$PACKAGES openal"
		STATIC_OPENAL=1
	fi
	shift
fi
if [[ "$1" = "--glfw" ]]; then
	PACKAGES="$PACKAGES glfw3"
	shift
fi
if ! [ -f .minimal-deps ]; then
	PACKAGES="$PACKAGES tesseract lept libpng16 cairo pixman-1 \
	    freetype2 opusfile opus ogg shapelib proj glewmx"
fi

PACKAGES="$PACKAGES libcurl openssl libxml-2.0 libpcre2-8 zlib"

PKG_CONFIG_PATH="\
$(pwd)/opus/opusfile-$ARCH/lib/pkgconfig:\
$(pwd)/opus/opus-$ARCH/lib/pkgconfig:\
$(pwd)/opus/libogg-$ARCH/install/lib/pkgconfig:\
$(pwd)/freetype/freetype-$ARCH/lib/pkgconfig:\
$(pwd)/libpng/libpng-$ARCH/lib/pkgconfig:\
$(pwd)/zlib/zlib-$ARCH/lib/pkgconfig:\
$(pwd)/cairo/cairo-$ARCH/lib/pkgconfig:\
$(pwd)/cairo/pixman-$ARCH/lib/pkgconfig:\
$(pwd)/curl/libcurl-$ARCH/lib/pkgconfig:\
$(pwd)/shapelib/libproj-$ARCH/lib/pkgconfig:\
$(pwd)/shapelib/libshape-$ARCH/lib/pkgconfig:\
$(pwd)/ssl/openssl-$ARCH/lib/pkgconfig:\
$(pwd)/ocr/liblept-$ARCH/lib/pkgconfig:\
$(pwd)/ocr/tesseract-$ARCH/lib/pkgconfig:\
$(pwd)/libxml2/libxml2-$ARCH/lib/pkgconfig:\
$(pwd)/openal-soft/openal-soft-1.20.1-$ARCH/build/install/lib/pkgconfig:\
$(pwd)/pcre2/pcre2-$ARCH/lib/pkgconfig:\
$(pwd)/glfw/glfw-$ARCH/install/lib/pkgconfig"

if [[ "$ARCH" == "linux-64" ]]; then
	PKG_CONFIG_PATH="$PKG_CONFIG_PATH:\
$(pwd)/glew/glew-1.13.0-$ARCH/install/lib64/pkgconfig:\
$(pwd)/libclipboard/libclipboard-$ARCH/install/lib/pkgconfig"
	PACKAGES="$PACKAGES libclipboard"
else
	PKG_CONFIG_PATH="$PKG_CONFIG_PATH:\
$(pwd)/glew/glew-1.13.0-$ARCH/install/lib/pkgconfig"
fi

export PKG_CONFIG_PATH

if [[ "$1" = "--cflags" ]]; then
	CGLM_EXTRA="-I$(pwd)/cglm/cglm-0.4.1/include"
	PCRE2_EXTRA="-DPCRE2_CODE_UNIT_WIDTH=8"
	if [[ "$ARCH" = "mac-64" ]]; then
		GLEW_EXTRA="-DLACF_GLEW_USE_NATIVE_TLS=0"
	fi
	LIBICONV="-I$(pwd)/libiconv/libiconv-$ARCH/include"
	ACFUTILS_EXTRA="-I$(pwd)/src"
elif [[ "$1" = "--libs" ]]; then
	if [[ "$ARCH" = "win-64" ]]; then
		# This must be appended AFTER --whole-archive, otherwise
		# it produces linkage errors on Windows.
		OPENSSL_EXTRA="-lcrypt32 -lws2_32 -lgdi32"
		DBGEXTRA="-ldbghelp -lpsapi"
		if [[ "$STATIC_OPENAL" = 1 ]]; then
			OPENAL_EXTRA="-lole32 -lwinmm"
		fi
	elif [[ "$ARCH" = "mac-64" ]]; then
		if [[ "$STATIC_OPENAL" = 1 ]]; then
			OPENAL_EXTRA="-lstdc++"
		fi
	fi
	LZMA="-L$(pwd)/lzma/qmake/$ARCH -llzma"
	LIBICONV="-L$(pwd)/libiconv/libiconv-$ARCH/lib -liconv -lcharset"

	if [[ "$ARCH" == "win-64" ]]; then
		ACFUTILS_EXTRA="-L$(pwd)/qmake/win64 -lacfutils"
	elif [[ "$ARCH" == "mac-64" ]]; then
		ACFUTILS_EXTRA="-L$(pwd)/qmake/mac64 -lacfutils"
	else
		ACFUTILS_EXTRA="-L$(pwd)/qmake/lin64 -lacfutils"
	fi

	if [[ "$ARCH" != "mac-64" ]]; then
		EXTRA="-static-libstdc++"
	fi
fi

echo $WHOLE_ARCH_ON ${ACFUTILS_EXTRA} ${LZMA} ${LIBICONV} \
    $(pkg-config $@ $PACKAGES) \
    $EXTRA $WHOLE_ARCH_OFF \
    $OPENSSL_EXTRA $DBGEXTRA ${CGLM_EXTRA} ${PCRE2_EXTRA} ${OPENAL_EXTRA} \
    ${GLEW_EXTRA}
