#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2024 Saso Kiselkov. All rights reserved.

source ../build_dep.common

CAIRO="cairo-1.16.0.tar.bz2"
PIXMAN="pixman-0.36.0.tar.bz2"

PIXMAN_PRODUCT="lib/libpixman-1.a"
PIXMAN_CONFOPTS_COMMON="--enable-static --disable-shared --disable-gtk \
    --disable-static-testprogs"

CAIRO_CFLAGS_COMMON="-I$(pwd)/pixman-0.36.0/pixman"
CAIRO_PRODUCT="lib/libcairo.a"
CAIRO_CONFOPTS_COMMON="--enable-static --enable-gl=no --enable-ft=yes \
    --disable-shared --enable-xlib=no --enable-xlib-xrender=no \
    --enable-xcb=no --enable-xlib-xcb=no --enable-xcb-shm=no --enable-qt=no \
    --enable-quartz=no --enable-quartz-font=no --enable-quartz-image=no \
    --enable-win32=no --enable-win32-font=no --enable-skia=no --enable-os2=no \
    --enable-beos=no --enable-drm=no --enable-gallium=no --enable-png=yes \
    --enable-glesv2=no --enable-cogl=no --enable-directfb=no --enable-vg=no \
    --enable-egl=no --enable-glx=no --enable-wgl=no --enable-script=no \
    --enable-fc=no --enable-ps=no --enable-pdf=no --enable-svg=no \
    --enable-full-testing=no --enable-interpreter=no \
    --enable-static-testprogs=yes --enable-gobject=no --enable-interpreter=no"

export PKG_CONFIG_PATH_IN="$(pwd)/../freetype/freetype-{PLATFORM}/lib/pkgconfig:\
$(pwd)/../zlib/zlib-{PLATFORM}/lib/pkgconfig:\
$(pwd)/../libpng/libpng-{PLATFORM}/lib/pkgconfig:\
$(pwd)/pixman-{PLATFORM}/lib/pkgconfig" \

CAIRO_PATCHES="cairo-win-ulongf.patch cairo-win-fopen.patch \
    cairo-scaled-font-mutex.patch"
if [[ "$do_dll" = 1 ]]; then
	CAIRO_PATCHES="$CAIRO_PATCHES cairo-win-dllexport.patch"
fi
PIXMAN_PATCHES="pixman-test-prng.patch pixman-visibility.patch"

case `uname` in
	Linux)
		CFLAGS="-m64\\ -g" LDFLAGS="-m64\\ -L$(pwd)/../freetype/freetype-linux-64/lib" \
		    CUSTPREMAKECMD="sed -i 's/^all:.*\$/all:/; s/^install:.*\$/install:/' test/Makefile" \
		    build_dep "linux-64" "$PIXMAN_CONFOPTS_COMMON" "$PIXMAN" \
		    "pixman" "$PIXMAN_PRODUCT" "$PIXMAN_PATCHES" && \
		    CUSTPREMAKECMD="sed -i 's/^all:.*\$/all:/; s/^install:.*\$/install:/' test/Makefile" \
		    build_dep "win-64" "$PIXMAN_CONFOPTS_COMMON \
		    --host=x86_64-w64-mingw32" \
		    "$PIXMAN" "pixman" "$PIXMAN_PRODUCT" "$PIXMAN_PATCHES" && \
		CFLAGS="$CAIRO_CFLAGS_COMMON\\ -g\\ -m64" LDFLAGS="-m64" \
		    build_dep "linux-64" "$CAIRO_CONFOPTS_COMMON" "$CAIRO" \
		    "cairo" "$CAIRO_PRODUCT" "$CAIRO_PATCHES" && \
		CFLAGS="$CAIRO_CFLAGS_COMMON\\ -m64" LIBS="-fstack-protector" \
		    build_dep "win-64" "$CAIRO_CONFOPTS_COMMON \
		    --host=x86_64-w64-mingw32" "$CAIRO" \
		    "cairo" "$CAIRO_PRODUCT" "$CAIRO_PATCHES"
		;;
	Darwin)
		# We must disable built-in support for thread-local-storage,
		# because it messes with VMProtect packed files on OSX.
		CUSTPREMAKECMD="gsed -i '/^#define TLS/d;' config.h" \
		CFLAGS="-m64" LDFLAGS="-m64" BUILD_SINGLE_THREADED=1 \
		    build_dep "mac-64" "$PIXMAN_CONFOPTS_COMMON" "$PIXMAN" \
		    "pixman" "$PIXMAN_PRODUCT" "$PIXMAN_PATCHES" && \
		CFLAGS="$CAIRO_CFLAGS_COMMON\\ -m64" LDFLAGS="-m64" \
		    build_dep "mac-64" "$CAIRO_CONFOPTS_COMMON" "$CAIRO" \
		    "cairo" "$CAIRO_PRODUCT" "$CAIRO_PATCHES"
		;;
	*)
		echo "Unsupported build platform" >&2
		exit 1
		;;
esac
