#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2024 Saso Kiselkov. All rights reserved.

source ../build_dep.common

LIBJPEG="jpegsrc.v9c.tar.bz2"

case `uname` in
	Linux)
		build_dep "linux-64" "--enable-static --disable-shared" \
		    "$LIBJPEG" "libjpeg" "lib/libjpeg.a" && \
		build_dep "win-64" "--enable-static --disable-shared \
		    --host=x86_64-w64-mingw32" \
		    "$LIBJPEG" "libjpeg" "lib/libjpeg.a"
		;;
	Darwin)
		CFLAGS="$CFLAGS_COMMON\\ -mmacosx-version-min=10.6" \
		    LDFLAGS="$LDFLAGS_COMMON\\ -mmacosx-version-min=10.6" \
		    build_dep "mac-64" "--enable-static --disable-shared" \
		    "$LIBJPEG" "libjpeg" "lib/libjpeg.a"
		;;
	*)
		echo "Unsupported build platform" >&2
		exit 1
		;;
esac
