#!/bin/sh

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2017 Saso Kiselkov. All rights reserved.

# We'll try to build on N+1 CPUs we have available. The extra +1 is to allow
# for one make instance to be blocking on disk.
NCPUS=$(( $(sysctl -n hw.ncpu) + 1 ))
LIB="liblzma.a"

rm -rf mac-32 mac-64
mkdir -p mac-32 mac-64

make distclean &> /dev/null

if [[ "$do_clean" = 1 ]]; then
	exit
fi

qmake -spec macx-clang && make -j $NCPUS && mv "$LIB" mac-64
if [ $? != 0 ] ; then
  exit
fi
