#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2024 Saso Kiselkov. All rights reserved.

source ../build_dep.common

PROJ4="proj-4.9.3.tar.bz2"
SHAPELIB="shapelib-1.4.1.tar.bz2"

if [[ "$do_clean" != 1 ]]; then
	PKG_CONFIG="pkg-config"
else
	PKG_CONFIG="true"
fi

if [ -z "$minimal" ]; then
	minimal=0
fi

case `uname` in
	Linux)
		build_dep "linux-64" "--enable-static --disable-shared" \
		    "$PROJ4" "libproj" "lib/libproj.a" && \
		build_dep "win-64" "--enable-static --disable-shared \
		    --host=x86_64-w64-mingw32" "$PROJ4" "libproj" \
		    "lib/libproj.a" && \
		build_dep "linux-64" "--enable-static --disable-shared \
		    --with-proj-cflags=$(PKG_CONFIG_PATH=libproj-linux-64/lib/pkgconfig \
		    $PKG_CONFIG --cflags proj) \
		    --with-proj-libs=$(PKG_CONFIG_PATH=libproj-linux-64/lib/pkgconfig \
		    $PKG_CONFIG --libs proj | sed 's/[[:space:]]/\\ /g')" \
		    "$SHAPELIB" "libshape" "lib/libshp.a"
		if [ "$minimal" -ne 1 ]; then
			build_dep "win-64" "--enable-static --disable-shared \
			    --host=x86_64-w64-mingw32 \
			    --with-proj-cflags='$(PKG_CONFIG_PATH=libproj-win-64/lib/pkgconfig \
			    $PKG_CONFIG --cflags proj)' \
			    --with-proj-libs='$(PKG_CONFIG_PATH=libproj-win-64/lib/pkgconfig \
			    $PKG_CONFIG --libs proj)'" \
			    "$SHAPELIB" "libshape" "lib/libshp.a"
		fi
		;;
	Darwin)
		build_dep "mac-64" "--enable-static --disable-shared" \
		    "$PROJ4" "libproj" "lib/libproj.a"  &&
		build_dep "mac-64" "--enable-static --disable-shared \
		    --with-proj-cflags='$(PKG_CONFIG_PATH=libproj-mac-64/lib/pkgconfig \
		    $PKG_CONFIG --cflags proj)' \
		    --with-proj-libs='$(PKG_CONFIG_PATH=libproj-mac-64/lib/pkgconfig \
		    $PKG_CONFIG --libs proj)'" \
		    "$SHAPELIB" "libshape" "lib/libshp.a"
		;;
	*)
		echo "Unsupported build platform" >&2
		exit 1
		;;
esac
