#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2017 Saso Kiselkov. All rights reserved.

# OpenSSL uses a fairly custom build infrastructure, so we can't
# use build_dep

OPENSSL="openssl-1.1.1g"

function build_ssl() {
	PLATFORM="$1"
	CONFOPTS="$2"

	OUTDIR="$(pwd)/openssl-$PLATFORM"

	(
		if [[ "$do_clean" = 1 ]]; then
			rm -rf "$OUTDIR" "$OPENSSL"
			return
		fi
		if [[ $(uname) = "Darwin" ]]; then
			CONFOPTS="$CONFOPTS -mmacosx-version-min=10.9"
		fi
		if ! [ -f "$OUTDIR/lib/libssl.a" ]; then
			rm -rf "$OUTDIR" "$OPENSSL"
			tar xzf "${OPENSSL}.tar.gz" || exit 1
			( cd "$OPENSSL" ;
			    patch -p1 < ../atexit_undefined.patch ) || exit 1
			mkdir -p "$OUTDIR"
			cd "$OPENSSL"
			./Configure no-shared no-dso --prefix="$OUTDIR" \
			    $CONFOPTS && \
			    make clean && \
			    make -j 8 && \
			    make install
		fi
	)
}

if [[ -z "$do_dll" ]]; then
	VIS="-fvisibility=hidden"
fi

case `uname` in
	Linux)
		build_ssl linux-64 "-fPIC -fvisibility=hidden linux-x86_64" || \
		    exit 1
		if [[ "$minimal" != 1 ]]; then
			build_ssl win-64 \
			    "--cross-compile-prefix=x86_64-w64-mingw32- $VIS mingw64"
		fi
		;;
	Darwin)
		build_ssl mac-64 "-fvisibility=hidden BSD-generic64"
		;;
	*)
		echo "Unsupported build platform" >&2
		exit 1
		;;
esac
