#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2018 Saso Kiselkov. All rights reserved.

source ../build_dep.common

PCRE2="pcre2-10.42.tar.xz"

case `uname` in
	Linux)
		CFLAGS="-DPCRE2_STATIC" build_dep "linux-64" \
		    "--enable-static --disable-shared" \
		    "$PCRE2" "pcre2" "lib/libpcre2-8.a" && \
		CFLAGS="-DPCRE2_STATIC" build_dep "win-64" "--enable-static --disable-shared \
		    --host=x86_64-w64-mingw32" \
		    "$PCRE2" "pcre2" "lib/libpcre2-8.a"
		;;
	Darwin)
		CFLAGS="-mmacosx-version-min=10.6\\ -DPCRE2_STATIC" \
		    LDFLAGS="-mmacosx-version-min=10.6" \
		    build_dep "mac-64" "--enable-static --disable-shared" \
		    "$PCRE2" "pcre2" "lib/libpcre2-8.a"
		;;
	*)
		echo "Unsupported build platform" >&2
		exit 1
		;;
esac
