#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2014 Saso Kiselkov. All rights reserved.

source ../build_dep.common

FREETYPE="freetype-2.8.1.tar.bz2"
FREETYPE_CONFOPTS_COMMON="--disable-shared --enable-static \
    --with-zlib=yes --with-bzip2=no --with-png=no \
    --with-harfbuzz=no --with-old-mac-fonts=no --with-fsspec=no \
    --with-fsref=no --with-quickdraw-toolbox=no \
    --with-quickdraw-carbon=no --with-ats=no"

if [[ "$do_dll" = 1 ]]; then
	FREETYPE_PATCH="freetype-win-dllexport.patch"
fi

export PKG_CONFIG_PATH_IN="$(pwd)/../zlib/zlib-{PLATFORM}/lib/pkgconfig"

case `uname` in
	Linux)
		CFLAGS="-m64" LDFLAGS="-m64" \
		    build_dep "linux-64" "$FREETYPE_CONFOPTS_COMMON" \
		    "$FREETYPE" "freetype" "lib/libfreetype.a" \
		    $FREETYPE_PATCH && \
		build_dep "win-64" "$FREETYPE_CONFOPTS_COMMON \
		    --enable-shared --host=x86_64-w64-mingw32" \
		    "$FREETYPE" "freetype" "lib/libfreetype.a" \
		    $FREETYPE_PATCH
		;;
	Darwin)
		CFLAGS="$FREETYPE_CFLAGS_COMMON" \
		    LDFLAGS="$FREETYPE_LDFLAGS_COMMON" \
		    build_dep "mac-64" "$FREETYPE_CONFOPTS_COMMON" \
		    "$FREETYPE" "freetype" "lib/libfreetype.a"
		;;
	*)
		echo "Unsupported build platform" >&2
		exit 1
		;;
esac
