#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2018 Saso Kiselkov. All rights reserved.

FILE="openal-soft-1.18.2.tar.bz2"
DIR="${FILE/%.tar.bz2/}"

[ -d "$DIR" ] || tar xjf "$FILE"

cd "$DIR/build"
cmake -DLIBTYPE=STATIC -DCMAKE_INSTALL_PREFIX=$(pwd)/linux-64 \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON ..
make -j 8 && make install
cd ..
