#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2017 Saso Kiselkov. All rights reserved.

# Invoke this script to build libacfutils for both Windows and Linux,
# 32- & 64-bit flavors. Install the necessary mingw cross-compile utilities
# first.
# On Linux also do "apt install libopenal-dev:x86_64 libopenal-dev:i386".

if [[ "$(uname)" = Darwin ]]; then
	echo "This is Mac, use build-mac instead!" 1>&2
	exit 1
fi

# We'll try to build on N+1 CPUs we have available. The extra +1 is to allow
# for one make instance to be blocking on disk.
NCPUS=$(( $(grep 'processor[[:space:]]\+:' /proc/cpuinfo  | wc -l) + 1 ))
RELEASE="debug"
DLL=0
WHOLE_ARCHIVE=0
DOCLEAN=1
LINUXONLY=0
DEBUG=0
NOERRORS=0
NOXPLM=0

rm -rf win32 win64 lin32 lin64
mkdir -p win64 lin64

while getopts "DdliEX" opt; do
	case "$opt" in
	D)
		DEBUG=1
		;;
	d)
		DLL=1
		WHOLE_ARCHIVE=1
		;;
	l)
		LINUXONLY=1
		;;
	i)
		DOCLEAN=0
		;;
	E)
		NOERRORS=1
		;;
	X)
		NOXPLM=1
		;;
	esac
done

qmake -set ACFUTILS_NOXPLM "$NOXPLM"

if [[ "$LINUXONLY" == 0 ]]; then
	make distclean > /dev/null
	qmake -set ACFUTILS_DLL $DLL
	qmake -set DEBUG $DEBUG
	qmake -set WHOLE_ARCHIVE $WHOLE_ARCHIVE
	qmake -set NOERRORS $NOERRORS
	qmake -set CROSS_COMPILE x86_64-w64-mingw32- && \
	    qmake -spec win32-g++ && make -j $NCPUS
	if [ $? != 0 ] ; then
		exit
	fi
	if [[ "$DLL" = 1 ]]; then
		VERSION="$(git describe --abbrev=0 --tags | \
		    sed 's/[[:alpha:].]//g; s/^0//g')"
		mv "$RELEASE/acfutils$VERSION.dll" \
		    "$RELEASE/libacfutils$VERSION.a" "win64" || exit 1
	else
		mv "$RELEASE/libacfutils.a" "win64/libacfutils.a" || exit 1
	fi
fi

if [[ "$DOCLEAN" == 1 ]]; then
	make distclean > /dev/null
fi
qmake -set DEBUG $DEBUG
qmake -set NOERRORS $NOERRORS
qmake -spec linux-g++-64 && make -j $NCPUS && mv libacfutils.a lin64
if [ $? != 0 ] ; then
  exit
fi

if [[ "$DOCLEAN" != 0 ]]; then
	make distclean > /dev/null
fi
