#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2024 Saso Kiselkov. All rights reserved.

source ../build_dep.common

LIBICONV="libiconv-1.16.tar.bz2"
LIBICONV_PRODUCT="lib/libiconv.a"
LIBICONV_CONFOPTS_COMMON="--enable-static --disable-shared"

case `uname` in
	Linux)
		build_dep "linux-64" "$LIBICONV_CONFOPTS_COMMON" "$LIBICONV" \
		    "libiconv" "$LIBICONV_PRODUCT" && \
		build_dep "win-64" "$LIBICONV_CONFOPTS_COMMON \
		    --host=x86_64-w64-mingw32" \
		    "$LIBICONV" "libiconv" "$LIBICONV_PRODUCT"
		# libiconv for Windows insists on putting in its own
		# resources files. Let's trash those.
		if [ -f libiconv-win-64/lib/libiconv.a ]; then
			rm -f libiconv-win-64/lib/libiconv.a && \
			ar rcs libiconv-win-64/lib/libiconv.a \
			    libiconv-win-64/lib/iconv.o \
			    libiconv-win-64/lib/localcharset.o \
			    libiconv-win-64/lib/relocatable.o
		fi
		;;
	Darwin)
		build_dep "mac-64" "$LIBICONV_CONFOPTS_COMMON" "$LIBICONV" \
		    "libiconv" "$LIBICONV_PRODUCT"
		;;
	*)
		echo "Unsupported build platform" >&2
		exit 1
		;;
esac
