#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2024 Saso Kiselkov. All rights reserved.

source ../build_dep.common

LIBPNG="libpng-1.6.50.tar.bz2"

case `uname` in
	Linux)
		CFLAGS="$CFLAGS_COMMON\\ -I$(pwd)/../zlib/zlib-linux-64/include\\ -m64" \
		    LDFLAGS="$LDFLAGS_COMMON\\ -m64\\ -L$(pwd)/../zlib/zlib-linux-64/lib" \
		    CUSTPREPCMD="ln -s \
		    $(pwd)/../zlib/zlib-linux-64/include/zconf.h && \
		    ln -s $(pwd)/../zlib/zlib-linux-64/include/zlib.h" \
		    build_dep "linux-64" "--enable-static --disable-shared" \
		    "$LIBPNG" "libpng" "lib/libpng16.a" && \
		CFLAGS="$CFLAGS_COMMON\\ -I$(pwd)/../zlib/zlib-win-64/include" \
		    LDFLAGS="$LDFLAGS_COMMON\\ -L$(pwd)/../zlib/zlib-win-64/lib" \
		    CUSTPREPCMD="ln -s $(pwd)/../zlib/zlib-win-64/include/zconf.h \
		    && ln -s $(pwd)/../zlib/zlib-win-64/include/zlib.h" \
		    build_dep "win-64" "--enable-static --disable-shared \
		    --host=x86_64-w64-mingw32" \
		    "$LIBPNG" "libpng" "lib/libpng16.a"
		;;
	Darwin)
        # This feels stupid, but libpng checks what architecture the *host* platform is running,
        # not what the target architecture is when deciding which optimisations to pick. And even
        # if we were building for arm64, the neon code doesn't compile
        #
        # --disable-arm-neon
		CFLAGS="$CFLAGS_COMMON\\ -mmacosx-version-min=10.6" \
		    LDFLAGS="$LDFLAGS_COMMON\\ -mmacosx-version-min=10.6" \
		    ARCH=x86_64 build_dep "mac-64" "--enable-static --disable-shared --disable-hardware-optimizations --disable-arm-neon" \
		    "$LIBPNG" "libpng" "lib/libpng16.a"
		;;
	*)
		echo "Unsupported build platform" >&2
		exit 1
		;;
esac
