#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2018 Saso Kiselkov. All rights reserved.

# This utility generates a syms.txt that the libacfutils' log_backtrace
# can read on Windows.

if [ -z "$1" ]; then
	echo "Missing argument. Usage: $0 win.xpl > syms.txt" >&2
	exit 1
fi

nm -n "$1" | egrep -i ' t | a __image_base__' | grep -iv '\.[a-z]\+'
