#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2023 Saso Kiselkov. All rights reserved.

# This utility generates a syms.txt that the libacfutils' log_backtrace
# can read on Windows.

if [ -z "$1" ]; then
	echo "Missing argument. Usage: $0 win.xpl > syms.txt" >&2
	exit 1
fi

# We need to grab the file offset of the .text section, as well as its
# section ID. This is then used to calculate the symbol offsets in absolute
# terms from the file load offset (obtained in find_module() as lpBaseOfDll).
# This way, all symbols correspond to their exact in-image locations and
# can be exactly precisely.
FILEOFF="$(objdump -h "$1" | awk '/\.text\>/{ print "0x" $6; }')"
SECID=$(( $(objdump -h "$1" | awk '/\.text\>/{ print $1; }' ) + 1 ))
objdump -j .text -t "$1" | cut -d ']' -f 2- | awk '
/sec  '"$SECID"'.*(ty   20)/{
	addr = strtonum($8);
	printf("%08x t %s\n", addr + '"$FILEOFF"', $9);
}
' | sort
